config/routes.rb
Stylist::Application.routes.draw do

  root :to => 'questions#home'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'retailers', to: 'pages#retailers'
  get 'pages/bookmarklet'
  get 'pages/image_picker'
  get 'pages/login'
  get 'answers/vote'
  resources :users
  resources :tags
  resources :questions do
    resources :answers
  end
  
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :points, :reply
  belongs_to :questions
  belongs_to :user
  before_create :default_values
  validates :user_id, presence: true
  validates :reply, presence: true

  def vote_up
    self.points +=1
    self.save
  end

  def vote_down
    self.points -=1
    self.save
  end

  private

  def default_values
    self.points ||= 0
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description, :image_url, :answered, :title, :tag_ids, :price, :product_url
  has_many :answers, :order => "points DESC", :dependent => :destroy
  belongs_to :user
  has_and_belongs_to_many :tags
  before_create :default_values
  validates :user_id, presence: true
  validates :image_url, presence: true
  validates :title, presence: true
  accepts_nested_attributes_for :tags

  scope :unanswered, where(answered: false).order("created_at DESC")

  def update_tags
    self.tags.each do |tag|
      tag.count += 1
      tag.save
    end
  end

  private

  def default_values
    self.answered ||= false
    self.image_url ||= "/default-image.jpg"
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :count, :title
  has_and_belongs_to_many :questions
  validates :title, :presence => true
  validates :title, :uniqueness => true

  def self.create_or_find(key)
    t = Tag.where(title: key).first_or_create(count:0)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid, :profile_picture_url, :points
  has_many :questions, :order => "created_at DESC", :dependent => :destroy 
  has_many :answers, :order => "created_at DESC", :dependent => :destroy
  has_many :vote_limits, :dependent => :destroy

  
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      if auth.provider = "facebook"
        user.profile_picture_url = "https://graph.facebook.com/#{auth.uid}/picture?width=463"
      else 
        user.profile_picture_url = "/default_image.jpg"
      end
      user.points = 0
      user.save!
    end
  end

  def votes(question_id)
    vote_limit = self.vote_limits.where(question_id: question_id).first
    if vote_limit.nil?
      self.vote_limits.create(question_id: question_id, votes: 1)
      return true
    else
      if vote_limit.votes > 2
        return false
      else
        vote_limit.votes += 1
        vote_limit.save
        return true
      end
    end
  end
 
end

app/models/vote_limit.rb
class VoteLimit < ActiveRecord::Base
  attr_accessible :votes, :user_id, :question_id
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  
  def create
    if current_user
      question = Question.find(params["question_id"])
      answer = question.answers.build(params["answer"])
      answer.user_id = current_user.id
      answer.save
      if answer.save
        redirect_to question_path(question.id)
      else
        redirect_to request.referer
      end
    else
      session[:answer] = params
      redirect_to modals_login_path
    end
  end

  def vote
    answer = Answer.find(params["answer_id"])
    if current_user.votes(answer.question_id)
      if params["up"] == "true"
        answer.vote_up
        answer.user.points += 1
        answer.user.save
      else
        answer.vote_down
        answer.user.points -= 1
        answer.user.save
      end
    end
    redirect_to question_path(answer.question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user 
end

app/controllers/modals_controller.rb
class ModalsController < ApplicationController
  before_filter :set_layout

  def bookmarklet

  end

  def login
    
  end

  def image_picker
    @images = params[:images]
  end

  private

  def set_layout
    @layout = "modal"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :set_layout, except: [:retailers]

  def retailers

  end

  def bookmarklet

  end

  def login
    
  end

  def image_picker
    @logged_in = current_user
    @images = JSON.parse(params["images"])
    @question = Question.new
  end

  private

  def set_layout
    @layout = "modal"
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def home
    @questions = Question.unanswered.limit(12)
    @layout = "home"
  end

  def index
    @questions = Question.unanswered
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.create(params[:question])
    current_user.points += 1
    current_user.save
    if @question.save
      @question.update_tags
      redirect_to question_path(@question.id)
    else
      redirect_to request.referer
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    redirect_to questions_path
  end
  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to edit_user_path(user.id)
    #redirect_to request.env["omniauth.origin"]
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  respond_to :html, :json, :xml

  def create
    @tag = Tag.create_or_find(params[:tag]["title"])
    respond_with @tag
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit
    if params[:id] == current_user.id.to_s
      @user = User.find(params[:id])
    else
      redirect_to root_url, :notice => "You are not authorized to view that page"
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_name(name)
    tmp = name.split(" ")
    display = "#{tmp[0]} #{tmp[1][0]}" 
  end
end

app/helpers/modals_helper.rb
module ModalsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Stylio
    = stylesheet_link_tag "application",
      "http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700", :media => "all"
    = favicon_link_tag(source="/favicon.gif")
    = javascript_include_tag "application"
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1.0"
  body
    - if @layout != "modal"
      #header
        .nav
          .panel-stylist.fixed
            .row.collapse
              .large-1.columns 
                a.logo href=root_url
              .large-5.columns 
                p.tagline shop smarter with our experts 
              .large-2.columns
                input type="text" placeholder="Search for a product, store or tag" 
              .large-2.columns
                - if current_user
                  a.sm-blue-bold href="#" = display_name(current_user.name)
                  a.sm-blue-bold  href=signout_path Sign Out
                - else
                  a.sm-blue-bold  data-reveal-id="login-modal" href="#" Login
                  a.sm-blue-bold  data-reveal-id="login-modal" href="#" Sign up

      #flash-message
        - if flash[:notice]
          p.notice
            = flash[:notice]
        - if flash[:error]
          p.error
            = flash[:error]

      #content
        =yield

      #login-modal.reveal-modal.small
        center
          h2 Login to post
          p
            a.button href="/auth/facebook" log in with facebook
          a.close-reveal-modal &#215;      
      #footer
        footer.footer-stylist
          .row
            .large-3.columns
              .title-white Women
              a Hand bags
              a Boots
              a Business wear
              a Jackets
              a Shoes
              a Dresses & Skirts
              a Yoga
              a > Under $500
              a > Under $100
            .large-3.columns
              .title-white Men
              a Suits & Ties
              a Sportswear
              a Hats
              a Jackets
              a Shoes & Boots
              a Scarfs
              a Cuff Links
              a > Under $500
              a > Under $100
            .large-3.columns
              .title-white Brands
              a 3.1 Phillip Lim
              a Celine
              a Chanel
              a Peter Pilotto
              a Proenza Schouler
              a Rebecca Minkoff
              a Rodarte
              a Skaist Taylor
              a Stella McCartney
            .large-3.columns
              .title-white Brands
              a Abigail Stewart
              a Carlos
              a Clips
              a Erro
              a Geren Ford
              a Paule Ka
              a Vivienne Westwood
              a Willow
              a Zucca
        footer.d-grey.title
          .row
            .large-4.columns
              a href="retailers" 
                | Stylist.io For Retailers
            .large-8.columns
              | Made by 
              a href='https://twitter.com/hadiyahdotme' @hadiyahdotme 
              | & 
              a href='https://twitter.com/emstar' @emstar
    - else
      =yield

app/views/pages/_bookmarklet.html.slim
center
  a.button.small.round.button-stylist href="javascript:(function(){document.body.appendChild(document.createElement('script')).src='http://#{request.host_with_port}/image_selector.js';})();" Stylio Clipper
  h4 Drag bookmarklet to your browser bar to start adding to your store

app/views/pages/image_picker.html.slim
javascript:
  jQuery('head').append("<base target='_blank'>");

  var imgSelect = function(_this){
    jQuery('#question_image_url').val(_this.src);
    jQuery('.thumbnail').css('border','0px');
    jQuery(_this).css('border','5px solid yellow');
  }

  var closeModal = function() {
    parent.postMessage("closed","*");
  }


- if @logged_in
  .row
    div style="float:right"
      a href="javascript: closeModal()"
        | close window
  .row
    h5 Please select your image
  .row
    - @images.each do |image|
      .small-2.columns
        img.thumbnail onclick="imgSelect(this)" src=image
  .row
    .large-4.columns
      = render "questions/form"
- else
  a.button.large href="/auth/facebook" log in with facebook

javascript:
  $("#question_submit_action .button").click(function() {
    closeModal();
  });

app/views/pages/login.html.slim
h2 Login to post
p
  a.button.large href="/auth/facebook" log in with facebook

app/views/pages/retailers.html.slim
.container-stylist
  .row
  center
    .large-12.columns
      h4 Want to integrate stylio into your site?
      br
  .row
    .large-8.large-centered.columns
      p.text-center Stylist is the place to ask your fashion & style questions, and have them answered by our large network of stylists. Your products can be tagged in questions and answers, and we can provide a code snippet for you to integrate q&a's into your site.  
  .row
  center
    .large-12.columns
      h4
        | Contact us at 
        a href="mailto:hello@styl.io" hello@styl.io

app/views/questions/_form.html.slim
#question_form
  = semantic_form_for @question do |f|
    .row
      = f.input :image_url, :as => :hidden
      = f.input :product_url, :input_html => { placeholder:" Insert url to Product Page" }
      = f.input :title, :label => "Short Description", :input_html => { maxlength:120 }
      = f.input :price, :input_html => {step:"0.25", style:"width:10%;"}
      = f.input :description, :label => "Details"
      p.left.tag-label Tags
      ul#tags
      = f.action :submit, :button_html => { class: "button small button-stylist-small" }

#image-picker
  h2.subheader
    | Select your image below

javascript:
  $("#question_product_url").change( function(){
    $.get( $("#question_product_url").val(), function(data){
      $(data.responseText).find('img').each(function(_this){
        var pattern = new RegExp("^(http|https)");
        if ((_this.width > 200) && (_this.height > 100))
          $('#image-picker').append("<div class='large-3 columns'><img src="+_this.src+" onclick='imgSelect();'></div>");
      });
    });
  });

  var imgSelect = function(_this){
    jQuery('#question_image_url').val(_this.src);
    jQuery('.thumbnail').css('border','0px');
    jQuery(_this).css('border','5px solid yellow');
  }
    
  $("#tags").tagit({ 

    beforeTagAdded: function(event, ui) {
      tag_x = ui.tag.text();
      tag = tag_x.substring(0,tag_x.length-1).toString();
      $.ajax({
        type:"Post",
        url: "http://" + location.host + "/tags",
        data: {tag: {title: ''+tag}},
        dataType: 'json',
        success: function(data) {
          $('#new_question').append("<input name='question[tag_ids][]' type='hidden' value="+data.id+" id="+data.title+">");
        }
      });
    },

    afterTagRemoved: function(event, ui) {
      tag_x = ui.tag.text();
      tag = tag_x.substring(0,tag_x.length-1).toString();
      $("#"+tag).remove();
    }

  });

app/views/questions/home.html.slim
.container-stylist
  .row
  center
    h4.title top-selling products
  .row.collapse
    .large-12.columns
      .question-grid
        - @questions.each do |question| 
          .large-4.columns
            .row-stylist
              .thumb-stylist
                = image_tag question.image_url
              a.product-name  href=question_path(question.id)
                = question.title
              .price
                |  $150
              br
              a.user-name
                |  Diyah's store
              .user-replies
                = question.answers.count
                |  products
              .user-replies
                = question.answers.count
                |  reviews

app/views/questions/index.html.slim
.container-stylist
  .row
  center
    h4.title top-selling products
  .row.collapse
    .large-12.columns
      .question-grid
        - @questions.each do |question| 
          .large-4.columns
            .row-stylist
              .thumb-stylist
                = image_tag question.image_url
              a.product-name  href=question_path(question.id)
                = question.title
              .price
                |  $150
              br
              a.user-name
                |  Diyah's store
              .user-replies
                = question.answers.count
                |  products
              .user-replies
                = question.answers.count
                |  reviews

app/views/questions/new.html.slim
.container-stylist
  .row
  center
    h4
      | Drag bookmarklet to your browser bar to start asking questions 
      br
    .row
    center
      a.button.small.round.button-stylist href="javascript:(function(){document.body.appendChild(document.createElement('script')).src='http://#{request.host_with_port}/image_selector.js';})();" Style Q&A
    |   ← Drag to your Bookmarks Bar
    
    = render "form"

app/views/questions/open.html.slim
.container-stylist
  .row
    .large-12.columns
      .title Recent Style Questions
  - @questions.each do |question|
    .row.row-stylist.collapse
      .large-4.columns
        .thumb-stylist
          = image_tag question.image_url
      .large-8.columns
        .row-content
          p
            strong
              = question.title
            br
            = question.description
          p
            a.button.button-stylist-small href=question_path(question.id) Show

app/views/questions/show.html.slim
.container-stylist
  .row
    .large-12.columns
      a.title href=questions_path ← Back
  .row
    .large-4.columns
      = image_tag @question.image_url
    .large-8.columns
      .row
        h2
          = @question.title
      .row 
        h4
          = @question.description
      .row
        .user-name
          | Posted by 
          = display_name(@question.user.name)
        .user-time
          = time_ago_in_words(@question.created_at)
          |  ago
        .user-replies
          = @question.answers.count
          |  replies
      .row
        h4 Tags
        - @question.tags.each do |tag|
          = " #{tag.title}"
      - @question.answers.each do |answer|
        .row
          div.replies
            .large-8.columns
              h2
                = display_name(answer.user.name)
                |  says:
              = answer.reply
            .large-1.columns
              .row
                -if current_user
                  .row
                    a href='/answers/vote?up=true&answer_id=#{answer.id}'
                      .up-arrow
                  .row.points
                    = answer.points
                  .row
                    a href='/answers/vote?up=false&answer_id=#{answer.id}'
                      .down-arrow
                - else
                  a data-reveal-id="login-modal" href="#" login to vote

      .row
        div.replies
          - if current_user
            = semantic_form_for [@question, @answer] do |f|
              = f.input :reply, :input_html => { maxlength: 140 }
              = f.action :submit, :button_html => { class:"button small button-stylist" }
          - else
            a.button.button-stylist data-reveal-id="login-modal" href="#" login to post a reply
      .row
        - if current_user.id == @question.user.id
          p
            //= link_to "Edit", edit_question_path(@question), style: "padding-right:10px;"
            = link_to "Delete", question_path(@question),
              confirm: "Are you sure you want to delete this question?", method: :delete

app/views/users/edit.html.slim
.container-stylist
  #profile-header
    .row
      .small-3.columns
        h2 = display_name(@user.name)
      .small-3.columns
        span.label.radius style="margin-right:5px"
          | Expert
        span.label.radius
          | Women's Vintage
      .small-6.columns
        .small-2.columns
          h5.subheader
            = @user.questions.count
            |  questions
        .small-2.columns
          h5.subheader
            = @user.answers.count
            |  answers
        .small-2.columns
          h5.subheader
            = @user.points
            |  points
    .row
      .small-6.columns
        h4.subheader This is where the bio goes
      .small-6.columns
        h6.subheader
          | joined 
          = time_tag(@user.created_at)

  #profile-details
    .row
      #profile-sidebar.large-4.columns
        = image_tag @user.profile_picture_url
        a.button.small.button-stylist href="#" Follow
      #profile-right-content.large-8.columns
        .row
          = render 'pages/bookmarklet'
        .row
          h2.subheader Featured Items
        .row
          .large-3.columns
            = image_tag "http://placehold.it/200x200&text=[img]"
          .large-3.columns
            = image_tag "http://placehold.it/200x200&text=[img]"
          .large-3.columns
            = image_tag "http://placehold.it/200x200&text=[img]"

    .row
      #profile-lower-content.large-12.columns
      .row 
        h2.subheader Recent Activity
      .row
        h2.subheader All Items
      .row
        .large-3.columns
          = image_tag "http://placehold.it/200x200&text=[img]"
        .large-3.columns
          = image_tag "http://placehold.it/200x200&text=[img]"
        .large-3.columns
          = image_tag "http://placehold.it/200x200&text=[img]"

app/views/users/show.html.slim
.container-stylist
.row
  .large-6.columns
    = image_tag @user.profile_picture_url
  .large-6.columns
    h2 = display_name(@user.name)
    | Stylist Tagline and bio
    p
      .small-6.columns
        | joined 
        = time_tag(@user.created_at)
      .small-6.columns
        a.button.small.button-stylist href="#" Follow
    p
      h4 =display_name(@user.name)
      | 's Style Stats
    p
      h1
        = @user.questions.count
        |  questions  
        = @user.answers.count
        |  answers
        = @user.points
        |  points
    .row
      h2 Style expert in:
.row
  h2 Top picks
  .large-3.columns
    | pic1
  .large-3.columns
    | pic2
  .large-3.columns
    | pic3
  .large-3.columne
    | pic4